### ISSUE TITLE
Discrepanza nella documentazione

### ISSUE THREAD

**Issue by arturu** [italia/bootstrap-italia-next#34]
Vorrei segnalare che in questo paragrafo https://bootstrap-italia-next-development.vercel.app/docs/menu-di-navigazione/header/#versioni-disponibili viene riportato:
```
La classe .theme-light-desktop modifica unicamente la versione desktop
```
Invece nell'esempio della navbar viene usata la classe `theme-light-desk` per applicare la variante light. La classe che funziona è `theme-light-desk`, invece usando `theme-light-desktop` non avviene nessun cambiamento.

**Comment by astagi** [comment]
Great catch @arturu! Fixato https://github.com/italia/bootstrap-italia-next/commit/e32624f248ba59c94290b63a28147780e9b0e0ed
