### ISSUE TITLE
Megamenu: se un link ha la classe active la label ha lo stesso colore dello sfondo

### ISSUE THREAD

**Issue by arturu** [italia/bootstrap-italia-next#40]
## Comportamento atteso
Se una voce del megamenu ha la classe `active` il colore di sfondo e il colore della label dovrebbero essere diversi.

## Comportamento attuale
La label e il background sono simili. Non si verifica con l'hover passando sopra con il mouse

![bug-active-megamenu](https://user-images.githubusercontent.com/4628942/171628429-f1713bce-4953-4b29-9910-69f735ff3855.png)

## Possibili soluzioni
Magari impostare come background `trasparent` che dovrebbe andare bene nel caso della variante `dark`.

**Comment by astagi** [comment]
Grazie @OscarBresolin !
