### ISSUE TITLE
Overflow lista

### ISSUE THREAD

**Issue by dvero23** [italia/bootstrap-italia-next#46]
## Comportamento atteso
A prescindere dalla lunghezza del testo nella lista, il testo rimane nel wrapper.
![image](https://user-images.githubusercontent.com/106613927/172365308-04af8c4a-65d4-4c78-8b7f-f1e5314dd6c2.png)

## Comportamento attuale
Testo non viene wrappato correttamente e fuoriesce (si verifica un overflow).
![image](https://user-images.githubusercontent.com/106613927/172365365-8a665a48-c7b6-46eb-b83d-8d3924af4c78.png)

## Possibili soluzioni

Aggiungere alla classe list-item `overflow-wrap: anywhere;`

**Comment by astagi** [comment]
@dvero23 grazie del repo! se hai fatto questa modifica in locale e vuoi aprire una pull request ben venga 🙌
