### ISSUE TITLE
Wrong text in social card image

### ISSUE THREAD

**Issue by bfabio** [italia/bootstrap-italia-next#8]
The social card image at https://github.com/italia/bootstrap-italia-next/blob/development/docs/assets/img/favicons/social-card.png says "Il tema Bootstrap 4 [...]", when it should say "Bootstrap 5".

**Comment by Fupete** [comment]
Andrei verso una social card senza testo. Solo immagine.

**Comment by Fupete** [comment]
Here follow a proposal for the new social card. What do u think? cc @astagi @gpeirolo 

![social-card](https://user-images.githubusercontent.com/6736103/158974087-fa02a777-7903-4825-b7e6-fa63f70d388c.png)

**Comment by astagi** [comment]
Cool @Fupete !
